version: '2'
services:
  node:
    image: node:8.8.1-alpine
    env_file:
      - ./.env
    volumes: 
      - ./:/app
    command: ash -c 'npm install; node app.js'
    working_dir: /app
    restart: on-failure
  db:
    image: postgres:11.1-alpine
    env_file:
      - ./.env
    ports:
      - 5432:5432